packages:
  - packages/*

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

patchedDependencies:
  '@arcgis/lumina@5.1.0-next.29': patches/@arcgis__lumina@5.1.0-next.29.patch

strictPeerDependencies: true
