import '@maxpatiiuk/web-components/components/mp-paragraph';
import '@maxpatiiuk/web-components/components/mp-header';
import '@maxpatiiuk/web-components/components/mp-subheader';
import '@maxpatiiuk/web-components/components/mp-link';
import '@maxpatiiuk/web-components/components/mp-list';
import '@maxpatiiuk/web-components/components/mp-image';
import '@maxpatiiuk/web-components/components/mp-youtube';
import '@maxpatiiuk/web-components/components/mp-vimeo';
import '@maxpatiiuk/web-components/components/mp-aside';
