export const projectOrder = [
  'spacetime',
  'alia',
  'calendar-plus',
  'text-hoarder',
  'query-builder',
  'accessibility-refactor',
  'project-ephemeris',
  'specify7-test-panel',
  'workbench',
  'weblate',
  'small-retail-management',
  'tetris-react',
  'geo-io',
  'interface-redesign',
  'goodreads-stats',
  'lifemapper',
  'usage-stats',
  'modernizing-usage-stats',
  'socksy-linen',
  'open-api',
  'pixelland',
  'portfolio',
  'tts-king',
  'taxa',
  'battleship',
] as const;
